language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

env:
  matrix:
    - CAKE_VERSION=3.3.*
    - CAKE_VERSION=3.4.*

before_install:
  - scripts/before_install.sh

script:
  - vendor/bin/codecept run && cd ../..
  - vendor/bin/phpcs --standard=PSR2 --extensions=php --ignore=tests/*_app src/ tests/
  - phpunit
